# Generated by Django 5.2.14 on 2026-07-29 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthEngineAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ee_project', models.CharField(max_length=255, verbose_name='proyecto GCP')),
                ('refresh_token_encrypted', models.TextField()),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='cliente OAuth')),
                ('client_secret_encrypted', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earthengine_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta Earth Engine',
                'verbose_name_plural': 'Cuentas Earth Engine',
            },
        ),
    ]
