# Generated by Django 5.2.14 on 2026-08-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earthengineaccount',
            options={'verbose_name': 'Earth Engine account', 'verbose_name_plural': 'Earth Engine accounts'},
        ),
        migrations.AlterField(
            model_name='earthengineaccount',
            name='client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='OAuth client'),
        ),
        migrations.AlterField(
            model_name='earthengineaccount',
            name='ee_project',
            field=models.CharField(max_length=255, verbose_name='GCP project'),
        ),
    ]
