# Generated by Django 5.2.14 on 2026-08-13 10:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyarea',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Outline the map is framed by. Without it the map frames the wetlands.', null=True, srid=4326, verbose_name='boundary'),
        ),
    ]
