# Generated by Django 5.2.14 on 2026-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_studyarea_boundary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wetland',
            options={'ordering': ('name',), 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AddField(
            model_name='wetland',
            name='deims_id',
            field=models.URLField(blank=True, verbose_name='DEIMS-SDR id'),
        ),
        migrations.AddField(
            model_name='wetland',
            name='kind',
            field=models.CharField(choices=[('ramsar', 'Ramsar site'), ('elter', 'eLTER site')], db_index=True, default='ramsar', max_length=16, verbose_name='kind'),
        ),
    ]
